- src/main/java/ododock/webserver/security/handler/DaoAuthenticationSuccessHandler.java
- src/main/java/ododock/webserver/security/handler/OAuth2LoginSuccessHandler.java
- src/main/java/ododock/webserver/security/response/UserPrincipal.java
- src/main/java/ododock/webserver/security/service/JwtService.java
- refactored token generation with UserPrincipal value obejct
- separate responsibilities between success handler and jwt service
> chore: refactor token generation

- src/main/java/ododock/webserver/security/config/SecurityConfig.java
- src/main/java/ododock/webserver/security/filter/RefreshTokenAuthenticationFilter.java
- src/main/resources/application-dev.yml
- src/test/java/ododock/webserver/common/TestSecurityConfig.java
- src/test/java/ododock/webserver/security/LogoutEndpointDocsTest.java
- src/test/java/ododock/webserver/security/SocialLoginEndpointDocsTest.java
- src/test/java/ododock/webserver/security/SocialLoginSuccessResultResponseDocs.java
- src/test/java/ododock/webserver/security/TokenRefreshEndpointDocsTest.java
- src/test/resources/application.yml
- add below endpoint docs 
- logout
- social login
- token reissue
> docs: security endpoints docs test

- src/main/java/ododock/webserver/security/config/SecurityConfig.java
- src/main/java/ododock/webserver/security/filter/RefreshTokenAuthenticationFilter.java
- src/main/java/ododock/webserver/security/handler/DaoAuthenticationSuccessHandler.java
- src/main/java/ododock/webserver/security/handler/TokenReissueSuccessHandler.java
- src/main/java/ododock/webserver/security/response/DaoUserDetails.java
- src/main/java/ododock/webserver/security/response/UserPrincipal.java
- src/main/java/ododock/webserver/security/service/AuthService.java
- src/main/java/ododock/webserver/security/service/JwtService.java
- src/main/java/ododock/webserver/security/util/RequestParameterMatcher.java
- src/test/java/ododock/webserver/common/TestSecurityConfig.java
- src/test/java/ododock/webserver/security/TokenRefreshEndpointDocsTest.java
- fix token reissue handler 
- remove authorities from token claims
> fix: token reissue handler

- src/test/java/ododock/webserver/controller/ArticleControllerDocsTest.java
- src/test/java/ododock/webserver/controller/CategoryControllerDocsTest.java
> docs: add endpoint descriptions

- src/main/java/ododock/webserver/security/config/MainWebSecurityConfig.java
- src/main/java/ododock/webserver/security/config/OAuth2SecurityConfig.java
- src/main/java/ododock/webserver/security/service/JwtService.java
- decouple security filter chain
- change JwtService bean annotation
> chore: decouple filter chain

- src/main/java/ododock/webserver/controller/CategoryController.java
- src/main/java/ododock/webserver/domain/article/Article.java
- src/main/java/ododock/webserver/domain/profile/Category.java
- src/main/java/ododock/webserver/domain/profile/Profile.java
- src/main/java/ododock/webserver/exception/ResourceNotFoundException.java
- src/main/java/ododock/webserver/repository/CategoryRepository.java
- src/main/java/ododock/webserver/request/CategoryCreate.java
- src/main/java/ododock/webserver/request/CategoryOrderUpdate.java
- src/main/java/ododock/webserver/request/CategoryUpdate.java
- src/main/java/ododock/webserver/response/ListResponse.java
- src/main/java/ododock/webserver/service/CategoryService.java
- src/test/java/ododock/webserver/controller/CategoryControllerDocsTest.java
- change category endpoint parameters
- add category order
- remove category list update
- add single category update
- add list response field
- add test code
> feature: categories update and with its order

- .github/workflows/gradle.yml
- src/main/java/ododock/webserver/security/config/MainWebSecurityConfig.java
- src/main/java/ododock/webserver/security/config/OAuth2SecurityConfig.java
- fix token validation from edit security config
> fix: fix token validation

- src/main/resources/application-dev.yml
- src/main/resources/application-local.yml
- src/main/resources/application-prod.yml
- src/main/resources/application.yml
- unify profile yml for local, dev, and production
- add properties for content query clients
> chore: unify profile yml

- src/main/java/ododock/webserver/security/service/JwtService.java
> chore: edit refresh token claim

- build.gradle
- src/main/java/ododock/webserver/config/DomainServiceConfig.java
- src/main/java/ododock/webserver/controller/AccountController.java
- src/main/java/ododock/webserver/domain/account/Account.java
- src/main/java/ododock/webserver/domain/account/VerificationInfo.java
- src/main/java/ododock/webserver/exception/ErrorCode.java
- src/main/java/ododock/webserver/exception/InvalidVerificationCodeException.java
- src/main/java/ododock/webserver/exception/VerificationCodeExpiredException.java
- src/main/java/ododock/webserver/request/account/CompleteDaoAccountRegister.java
- src/main/java/ododock/webserver/request/account/CompleteSocialAccountRegister.java
- src/main/java/ododock/webserver/request/account/RequestVerificationCode.java
- src/main/java/ododock/webserver/security/config/MainWebSecurityConfig.java
- src/main/java/ododock/webserver/security/service/AuthService.java
- src/main/java/ododock/webserver/service/AccountService.java
- src/main/java/ododock/webserver/service/GMailService.java
- src/main/java/ododock/webserver/service/MailService.java
- src/main/java/ododock/webserver/util/CodeGenerator.java
- src/main/resources/application.yml
- src/test/java/ododock/webserver/controller/AccountControllerDocsTest.java
- src/test/java/ododock/webserver/controller/ProfileControllerDocsTest.java
- src/test/java/ododock/webserver/security/LoginEndpointDocsTest.java
- src/test/java/ododock/webserver/security/SocialLoginEndpointDocsTest.java
- src/test/java/ododock/webserver/security/TokenRefreshEndpointDocsTest.java
- src/test/java/ododock/webserver/service/AccountServiceTest.java
- src/test/resources/application.yml
- add email verification service component
- edit dao account register process flow
- add test codes for email verification related endpint
- polish codes
> feature: email verification service

- src/main/java/ododock/webserver/security/config/MainWebSecurityConfig.java
- src/main/java/ododock/webserver/security/filter/DaoAuthenticationFilter.java
- src/main/java/ododock/webserver/security/handler/MainAuthenticationFailureHandler.java
- src/main/java/ododock/webserver/security/service/AuthService.java
- polish exception handling process
> chore: polish exception handling

- src/main/java/ododock/webserver/controller/AccountController.java
- src/main/java/ododock/webserver/controller/VerificationController.java
- src/main/java/ododock/webserver/domain/account/Account.java
- src/main/java/ododock/webserver/domain/account/VerificationInfo.java
- src/main/java/ododock/webserver/repository/VerificationInfoRepository.java
- src/main/java/ododock/webserver/request/account/AccountPasswordReset.java
- src/main/java/ododock/webserver/request/account/CompleteDaoAccountVerification.java
- src/main/java/ododock/webserver/request/account/OAuthAccountMerge.java
- src/main/java/ododock/webserver/service/AccountService.java
- src/main/java/ododock/webserver/service/VerificationService.java
- src/test/java/ododock/webserver/controller/AccountControllerDocsTest.java
- src/test/java/ododock/webserver/controller/VerificationControllerDocsTest.java
- src/test/java/ododock/webserver/security/LoginEndpointDocsTest.java
- src/test/java/ododock/webserver/security/SocialLoginEndpointDocsTest.java
- src/test/java/ododock/webserver/security/SocialLoginSuccessResultResponseDocs.java
- src/test/java/ododock/webserver/service/AccountQueryServiceTest.java
- src/test/java/ododock/webserver/service/AccountServiceTest.java
- src/test/java/ododock/webserver/service/ProfileServiceTest.java
- decoupled Verification service from Account
- apply changes on test codes
- edit request DTO fields
- remove response DTO from non-GET endpoints
> refactor: decouple verification from account

- src/main/java/ododock/webserver/domain/article/Article.java
- src/main/java/ododock/webserver/domain/article/Category.java
- src/main/java/ododock/webserver/domain/article/dto/V1alpha1BaseBlock.java
- src/main/java/ododock/webserver/domain/article/dto/V1alpha1DefaultProps.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/article/V1alpha1Article.java
- src/test/java/ododock/webserver/controller/V1alpha1ArticleControllerDocsTest.java
- remove db ref from mongodb documents
- apply not required fields from controller dtos
- update controller docs test
> fix: remove db ref

- build.gradle
- src/main/java/ododock/webserver/security/config/ActuatorSecurityConfig.java
- src/main/java/ododock/webserver/security/config/BasicAuthProperties.java
- src/main/java/ododock/webserver/security/config/MainWebSecurityConfig.java
- src/main/java/ododock/webserver/web/ResourcePath.java
- src/main/resources/application-actuator.yml
- src/main/resources/application.yml
- src/test/java/ododock/webserver/common/TestMvcSecurityConfig.java
- add actuator configuration
- add actuator profile
- add basic authentication for actuator
> chore: add actuator config

- build.gradle
> chore: polish build tasks

- docker-compose.yml
- this is test commit. should be removed.
> chore: test-commit

- Dockerfile
- kubernetes/oddk-backend/.helmignore
- kubernetes/oddk-backend/Chart.yaml
- kubernetes/oddk-backend/templates/NOTES.txt
- kubernetes/oddk-backend/templates/_helpers.tpl
- kubernetes/oddk-backend/templates/backend-config.yaml
- kubernetes/oddk-backend/templates/backend-deployment.yaml
- kubernetes/oddk-backend/templates/backend-ingress.yaml
- kubernetes/oddk-backend/templates/backend-pvc.yaml
- kubernetes/oddk-backend/templates/backend-secret.yaml
- kubernetes/oddk-backend/templates/backend-service.yaml
- kubernetes/oddk-backend/templates/mongo-config.yaml
- kubernetes/oddk-backend/templates/mongo-secret.yaml
- kubernetes/oddk-backend/templates/mongo-service.yaml
- kubernetes/oddk-backend/templates/mongo-statefulset.yaml
- kubernetes/oddk-backend/templates/mysql-config.yaml
- kubernetes/oddk-backend/templates/mysql-secret.yaml
- kubernetes/oddk-backend/templates/mysql-service.yaml
- kubernetes/oddk-backend/templates/mysql-statefulset.yaml
- kubernetes/oddk-backend/templates/tests/test-connection.yaml
- kubernetes/oddk-backend/values.yaml
- src/main/resources/application.yml
- add helm chart for kubernetes deployment
> chore: kubernetes deployment configuration

- src/main/java/ododock/webserver/domain/BaseTimeEntity.java
- src/main/java/ododock/webserver/domain/profile/Profile.java
- src/main/java/ododock/webserver/domain/profile/SimpleProfileService.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/V1alpha1Base.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/V1alpha1BaseTime.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/account/V1alpha1Account.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/account/V1alpha1Profile.java
- src/main/resources/application.yml
- src/test/java/ododock/webserver/controller/V1alpha1AccountQueryControllerDocsTest.java
- src/test/java/ododock/webserver/controller/V1alpha1ArticleControllerDocsTest.java
- src/test/java/ododock/webserver/controller/V1alpha1CategoryControllerDocsTest.java
- change date format to ISO8601
> chore: change date type

- src/main/java/ododock/webserver/domain/article/Category.java
- src/main/java/ododock/webserver/domain/article/CategoryService.java
- src/main/java/ododock/webserver/domain/article/ReactiveCategoryService.java
- src/main/java/ododock/webserver/repository/reactive/CategoryRepository.java
- src/main/java/ododock/webserver/web/v1alpha1/V1alpha1CategoryController.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/category/V1alpha1Category.java
- src/test/java/ododock/webserver/controller/V1alpha1CategoryControllerDocsTest.java
- set position when create new category
- reorder when category position changed
- add api endpoint docs
> feature: manage category order

- src/main/java/ododock/webserver/domain/article/Article.java
- src/main/java/ododock/webserver/domain/article/ArticleExcerptor.java
- src/main/java/ododock/webserver/domain/article/BlockUtils.java
- src/main/java/ododock/webserver/domain/article/ReactiveArticleService.java
- src/main/java/ododock/webserver/web/v1alpha1/V1alpha1CategoryController.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/article/V1alpha1Article.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/article/V1alpha1ArticleSummary.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/category/V1alpha1Category.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/category/V1alpha1CategoryList.java
- src/test/java/ododock/webserver/controller/V1alpha1ArticleControllerDocsTest.java
- src/test/java/ododock/webserver/controller/V1alpha1CategoryControllerDocsTest.java
- src/test/java/ododock/webserver/domain/BlockNodeExcerptTest.java
- src/test/java/ododock/webserver/domain/BlockNodeJsonTest.java
- add article excerpt
- add article excerpt on response dto 
- add test code for extracting excerpt from article body
> feature: add article excerpts

- src/main/java/ododock/webserver/config/MongoConfig.java
- src/main/java/ododock/webserver/domain/article/Article.java
- src/main/java/ododock/webserver/domain/article/ArticleExcerptor.java
- src/main/java/ododock/webserver/domain/article/ArticleListOptions.java
- src/main/java/ododock/webserver/domain/article/ArticleQueryService.java
- src/main/java/ododock/webserver/domain/article/ArticleService.java
- src/main/java/ododock/webserver/domain/article/ReactiveArticleQueryService.java
- src/main/java/ododock/webserver/domain/article/ReactiveArticleService.java
- src/main/java/ododock/webserver/repository/QueryCriteriaUtils.java
- src/main/java/ododock/webserver/web/v1alpha1/V1alpha1ArticleController.java
- src/main/java/ododock/webserver/web/v1alpha1/dto/article/V1alpha1ArticleListOptions.java
- src/test/java/ododock/webserver/controller/V1alpha1ArticleControllerDocsTest.java
- src/test/java/ododock/webserver/domain/BlockNodeExcerptTest.java
- add article list search with query params
- add reactive article query service
- update controller docs test and other unit test as well
- add plain text field on Article Document
> feat: add article query params
